configfile: "configs/snakemake.json"

import os
import sys
sys.path.append(os.path.realpath(os.curdir))

dfe = config['data_file_ending']

rule all:
  input:
    expand('reports/figures/XXX.{pfe}', pfe=config['plot_file_ending']),

rule XXX:
  input:
    'data/processed/XXX.'+dfe
  output:
    'report/figures/XXX.{pfe}'
  shell:
    'python3 src/visualization/{rule}.py {input} {output}'

rule :
  input:
    'XXX'
  output:
    'data/processed/{rule}.'+dfe
  shell:
    'python3 src/data/{rule}.py {input} {output}'

